server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 0;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;

    location /api/ {
        proxy_pass http://api:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }

    location = /manifest.webmanifest {
        add_header Cache-Control "public, max-age=3600";
        try_files $uri =404;
    }

    location = /ngsw-worker.js {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location = /ngsw.json {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
