upload_limit_exceeded = "upload_limit_exceeded"
unsupported_media_type = "unsupported_media_type"
version_conflict = "version_conflict"
invalid_cursor = "invalid_cursor"
ssrf_blocked = "ssrf_blocked"
url_fetch_failed = "url_fetch_failed"